// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDMowuQJy6HOQp_7hqX96sFQLGkQZI58s',
    appId: '1:424004257168:web:e2a8c3f7024c2d6ed75f15',
    messagingSenderId: '424004257168',
    projectId: 'closet-be6fc',
    authDomain: 'closet-be6fc.firebaseapp.com',
    storageBucket: 'closet-be6fc.firebasestorage.app',
    measurementId: 'G-DBG5EMNTQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNTIVKCBTr1Ocy7SoMLnq-4dPoyfUFO4',
    appId: '1:424004257168:android:47b1e188c5889134d75f15',
    messagingSenderId: '424004257168',
    projectId: 'closet-be6fc',
    storageBucket: 'closet-be6fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJCSihntV1UteJc0poqcIYZm9FSV2Db6k',
    appId: '1:424004257168:ios:a503ea9b30742eced75f15',
    messagingSenderId: '424004257168',
    projectId: 'closet-be6fc',
    storageBucket: 'closet-be6fc.firebasestorage.app',
    iosBundleId: 'com.example.last3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJCSihntV1UteJc0poqcIYZm9FSV2Db6k',
    appId: '1:424004257168:ios:a503ea9b30742eced75f15',
    messagingSenderId: '424004257168',
    projectId: 'closet-be6fc',
    storageBucket: 'closet-be6fc.firebasestorage.app',
    iosBundleId: 'com.example.last3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDMowuQJy6HOQp_7hqX96sFQLGkQZI58s',
    appId: '1:424004257168:web:22d0bf573d052e04d75f15',
    messagingSenderId: '424004257168',
    projectId: 'closet-be6fc',
    authDomain: 'closet-be6fc.firebaseapp.com',
    storageBucket: 'closet-be6fc.firebasestorage.app',
    measurementId: 'G-9NSF16HTS8',
  );

}